[package]
name = "fnv_crack"
version = "0.1.0"
authors = ["Ian Palleiko <ian.palleiko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
workctl = "0.1.1"
